trigger:
- main

parameters:
  - name: browser
    displayName: Browser Choice
    type: string
    default: chrome
    values:
      - chrome
      - edge
      - firefox

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: NodeTool@0
  inputs:
    versionSpec: "14.x"
  displayName: "Install Node.js"

- script: |
    npm install
  displayName: "Install dependencies"

- script: |
    npm run pretest && npm run UI:E2E:test --browser $(browser) --continue-on-error merge:reports merge:json:report generate:html:report
  displayName: "UI E2E Tests"
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'Junit'
    testRunTitle: 'UI E2E results'
    testResultsFiles: '**/cypress/results/junit/report.xml'
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/cypress/results/html-report'
    artifact: 'UI Test Report'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()

- script: |
    npm run API:test:merge:upload 
  displayName: "API E2E Tests"
  continueOnError: true
  condition: succeededOrFailed()

- task: PublishTestResults@1
  inputs:
    testRunTitle: 'API E2E results'
    testResultsFiles: '**/cypress/results/junit/report.xml'
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/cypress/results/html-report'
    artifact: 'API Test Report'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()