
trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: NodeTool@0
  inputs:
    versionSpec: "14.x"
  displayName: "Install Node.js"

- script: |
    npm install
    displayName: "Install dependencies"

- script: |
    npm run UI:E2E:test:merge:upload
    displayName: "UI E2E Tests"
    continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'Junit'
    testRunTitle: 'UI E2E results'
    testResultsFiles: '**/cypress/results/junit/report.xml'
  condition: succeededOrFailed()